[package]
name                      = "ipfs-api"
description               = "Implementation of an IPFS HTTP API client"
authors                   = ["Ferris Tseng <ferristseng@fastmail.fm>"]
edition                   = "2018"
documentation             = "https://docs.rs/ipfs-api"
repository                = "https://github.com/ferristseng/rust-ipfs-api"
keywords                  = ["ipfs"]
categories                = ["filesystem", "web-programming"]
version                   = "0.5.2"
readme                    = "../README.md"
license                   = "MIT OR Apache-2.0"

[badges]
travis-ci                 = { repository = "ferristseng/rust-ipfs-api" }

[features]
default                   = ["hyper", "hyper-multipart-rfc7578", "hyper-rustls", "failure"]
actix                     = ["actix-http", "actix-multipart-rfc7578", "awc", "derive_more"]

[dependencies]
actix-http                = { version = "0.2", optional = true }
actix-multipart-rfc7578   = { version = "0.2", optional = true }
awc                       = { version = "0.2", optional = true }
bytes                     = "0.4"
derive_more               = { version = "0.15.0", optional = true }
failure                   = { version = "0.1.2", optional = true }
futures                   = "0.1"
http                      = "0.1"
hyper                     = { version = "0.12", optional = true }
hyper-tls                 = { version = "0.3.2", optional = true }
hyper-rustls              = { version = "0.17.1", optional = true }
hyper-multipart-rfc7578   = { version = "0.3", optional = true }
serde                     = { version = "1.0", features = ["derive"] }
serde_json                = "1.0"
serde_urlencoded          = "0.5"
tokio                     = "0.1"
tokio-codec               = "0.1"
tokio-io                  = "0.1"
walkdir                   = "2.2"
dirs                      = "1.0"
multiaddr                 = "0.3.1"

[dev-dependencies]
actix-http                = "0.2"
actix-multipart-rfc7578   = "0.2"
actix-rt                  = "0.2"
awc                       = "0.2"
hyper                     = "0.12"
hyper-tls                 = "0.3.2"
hyper-rustls              = "0.17.1"
tokio-timer               = "0.2"
tar                       = "0.4"
